# Generated by Django 3.1.13 on 2021-11-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gunshop', '0002_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lectrue_name',
            new_name='lecture_name',
        ),
    ]
