# Generated by Django 3.1.13 on 2021-11-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salooncategory',
            name='upper_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saloon.salooncategory'),
        ),
    ]
