# Generated by Django 3.1.13 on 2021-11-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='guild_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guild_master', to='gamification.gamificationinterface', verbose_name='guild master'),
        ),
    ]
