# Generated by Django 3.1.13 on 2021-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_auto_20211122_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveldefinition',
            options={},
        ),
        migrations.RemoveField(
            model_name='leveldefinition',
            name='level_phase',
        ),
        migrations.AddField(
            model_name='leveldefinition',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
