# Generated by Django 3.1.13 on 2021-11-27 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('is_business', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='members')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodology', models.CharField(choices=[('AG', 'Agile'), ('WF', 'Waterfall'), ('HB', 'Hybrid'), ('CT', 'Custom')], default='AG', max_length=2)),
                ('objective', models.TextField(verbose_name='Project Objective')),
                ('github_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ranch.workspace')),
            ],
        ),
    ]
