# Generated by Django 3.1.13 on 2021-11-10 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RailroadInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'railroad interface',
                'verbose_name_plural': 'railroad interfaces',
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('gun_type', models.CharField(max_length=20, verbose_name='총 종류')),
                ('name', models.CharField(max_length=500, verbose_name='gun_name')),
                ('description', models.TextField(verbose_name='gun_description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railroad.railroadinterface', verbose_name='소유자')),
            ],
            options={
                'verbose_name': 'Shotgun',
                'verbose_name_plural': 'Shotguns',
            },
        ),
    ]
